### ISSUE TITLE
remove line breaks from closure compiler output

### ISSUE THREAD

**Issue by dustinhorton** [cgutierrez/JsMinifier#1]
don't know if this runs any risks, but i dislike when the output isn't minified to a single line.

**Comment by concavelenz** [comment]
The Closure Compiler Java API has an option for this, CompilerOptions. setLineLengthThreshold(0) should do the trick

**Comment by dustinhorton** [comment]
the plugin isn't using the java api...i don't believe it supports raw js.

**Comment by cgutierrez** [comment]
This appears to actually be a feature of minifiers. UglifyJs does this as well. 
checkout http://code.google.com/closure/compiler/faq.html#linefeeds

"Why are there random line feeds in compiled scripts?"
