### ISSUE TITLE
Minify 2 or more files?

### ISSUE THREAD

**Issue by glebovsky** [cgutierrez/JsMinifier#13]
Hello!

Is there a way to minify 2 or more files in one?

**Comment by cgutierrez** [comment]
Unfortunately, this is currently not possible. If you have thoughts on how it could work, I'd love to hear them. One potential way would be to first create the file that you want as your "result" file... then add some special comments in the file that could be used to inject other scripts in to your file. So something like...

// js_min_include somefile.js
// js_min_include another_file.js
// js_min_include another_file.js

The resulting file would have those scripts minified and in the specified order.  Aside from that, it might be best to use another tool to concat and minify javascripts. The biggest downside to this obviously is that it would be editor/plugin specific.
