### ISSUE TITLE
Package doesn't work at all

### ISSUE THREAD

**Issue by martinkadlec0** [cgutierrez/JsMinifier#2]
Hi,
I'm using the latest version of ST2 (build-2165) with Package manager. I tried to install this minifier but it doesn't seem to work. Ctrl+alt+m does nothing and when I try to use the command in console it doesn't knew it.

I tried to reinstall it (JS-Minifier) and restart ST2 several times, but nothing helped me.

Any ideas?

**Comment by cgutierrez** [comment]
hmmm. thats odd! can you tell me OS you're using so I can debug it?

**Comment by martinkadlec0** [comment]
Win7 64bit

**Comment by martinkadlec0** [comment]
If it will work for you there then It might be some problem related to my computer. In that case could you help me please? (Do you use some IM?)

**Comment by cgutierrez** [comment]
I haven't tested it on Windows yet. Let me test it Windows. If it doesn't work, I'll make any fixes and post an update.

**Comment by martinkadlec0** [comment]
Thank you

**Comment by cgutierrez** [comment]
I've tested it on two separate Windows 7 machines, 1 32 bit and 1 64bit and both worked fine. I did find a bug for when there are errors in the javascript. In this case, closure doesn't return anything. I'm adding a separate issue for this.

**Comment by martinkadlec0** [comment]
It somehow started working ... I don't have any idea what happened but I'm glad it did :)

**Comment by cgutierrez** [comment]
great! glad to hear it. I'm working on an updated version that I hope to release in the next few days as well. Hopefully that will work for you as well :)
