### ISSUE TITLE
Minify /bar/foo.js (current buffer) into /bar/foo.min.js

### ISSUE THREAD

**Issue by eoinkelly** [cgutierrez/JsMinifier#8]
Hi,
Useful plugin - good job. I have a feature request/idea:

I really like being able to minify from Sublime but it would be more useful to me if the minified file was saved separately e.g.  /project/foo.js (open in the current buffer) minified into /project/foo.min.js rather than replacing the contents of the current buffer. Perhaps the behaviour could be hooked up to a different key combination or controlled by a setting in the user preferences hash. 

 This would link up nicely with SFTP's file monitoring to automatically push the minfied version to the server.

Thanks for your time
/Eoin/

**Comment by cgutierrez** [comment]
Sounds like a good idea to me. I'll see what I can do about adding it soon.

**Comment by skoch** [comment]
I second this behavior.

**Comment by cgutierrez** [comment]
I added this with the key binding of `ctrl+alt+shift+m`... kind of a shitty binding but I figure it can be remapped if it's something you use often enough.

let me know if you have any issues.

**Comment by eoinkelly** [comment]
Awesome - thanks.
